modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/easy-piglins/issues"
[[mods]]
modId = "easy_piglins"
version = "${mod_version}"
displayName = "Easy Piglins"
updateJSONURL = "https://update.maxhenkel.de/neoforge/easy_piglins"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/easy-piglins"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''Easy Piglins'''
[[dependencies.easy_piglins]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.easy_piglins]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"